import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <nav>
          <Link  href= "/">
          <button>Home</button>
          </Link>
          <Link  href= "/posts">
          <button>Posts</button>
          </Link>
          <Link  href= "/about">
          <button>About</button>
          </Link>
        </nav>
      </body>
    </html>
  );
}
